[workspace]
resolver = "2"
members = [
    "crates/beambin-core",
    "crates/beambin",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
# panic = "abort"
panic = "unwind"
strip = true
