port = 8080
host = "https://example1.com"
blocked_hosts = ["https://example.com", "https://example2.com"]

name = "Beambin"
description = "My Beambin instance"

real_ip_header = "CF-Connecting-IP"
snowflake_server_id = 1234567890

[captcha]
# CHANGE THIS
site_key = "10000000-ffff-ffff-ffff-000000000001"
secret = "0x0000000000000000000000000000000000000000"
